lwp/views/main.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function
import os
import re
import time
import socket
import subprocess
import ConfigParser

from flask import Blueprint, request, session, g, redirect, url_for, abort, render_template, flash, jsonify

import lwp
import lwp.lxclite as lxc
from lwp.utils import query_db, if_logged_in, get_bucket_token, hash_passwd, read_config_file, cgroup_ext
from lwp.views.auth import AUTH

# TODO: see if we can move this block somewhere better
try:
    config = read_config_file()
    USE_BUCKET = config.getboolean('global', 'buckets')
    BUCKET_HOST = config.get('buckets', 'buckets_host')
    BUCKET_PORT = config.get('buckets', 'buckets_port')
except ConfigParser.NoOptionError:
    USE_BUCKET = False
    print("- Bucket feature disabled")


storage_repos = config.items('storage_repository')

# Flask module
mod = Blueprint('main', __name__)


@mod.route('/')
@mod.route('/home')
@if_logged_in()
def home():
    """
    home page function
    """
    listx = lxc.listx()
    containers_all = []

    for status in ('RUNNING', 'FROZEN', 'STOPPED'):
        containers_by_status = []

        for container in listx[status]:
            container_info = {
                'name': container,
                'settings': lwp.get_container_settings(container, status),
                'memusg': 0,
                'bucket': get_bucket_token(container)
            }

            containers_by_status.append(container_info)
        containers_all.append({
            'status': status.lower(),
            'containers': containers_by_status
        })
        clonable_containers = listx['STOPPED']

    return render_template('index.html', containers=lxc.ls(), containers_all=containers_all, dist=lwp.name_distro(),
                           host=socket.gethostname(), templates=lwp.get_templates_list(), storage_repos=storage_repos,
                           auth=AUTH, clonable_containers=clonable_containers)


@mod.route('/about')
@if_logged_in()
def about():
    """
    about page
    """
    return render_template('about.html', containers=lxc.ls(), version=lwp.check_version())


@mod.route('/<container>/edit', methods=['POST', 'GET'])
@if_logged_in()
def edit(container=None):
    """
    edit containers page and actions if form post request
    """
    host_memory = lwp.host_memory_usage()
    cfg = lwp.get_container_settings(container)

    if request.method == 'POST':
        form = request.form.copy()

        if form['bucket'] != get_bucket_token(container):
            g.db.execute("INSERT INTO machine(machine_name, bucket_token) VALUES (?, ?)", [container, form['bucket']])
            g.db.commit()
            flash(u'Bucket config for %s saved' % container, 'success')

        # convert boolean in correct value for lxc, if checkbox is inset value is not submitted inside POST
        form['flags'] = 'up' if 'flags' in form else 'down'
        form['start_auto'] = '1' if 'start_auto' in form else '0'

        # if memlimits/memswlimit is at max values unset form values
        if int(form['memlimit']) == host_memory['total']:
            form['memlimit'] = ''
        if int(form['swlimit']) == host_memory['total'] * 2:
            form['swlimit'] = ''

        for option in form.keys():
            # if the key is supported AND is different
            if option in cfg.keys() and form[option] != cfg[option]:
                # validate value with regex
                if re.match(cgroup_ext[option][1], form[option]):
                    lwp.push_config_value(cgroup_ext[option][0], form[option], container=container)
                    flash(cgroup_ext[option][2], 'success')
                else:
                    flash('Cannot validate value for option {}. Unsaved!'.format(option), 'error')

        # we should re-read container configuration now to be coherent with the newly saved values
        cfg = lwp.get_container_settings(container)

    info = lxc.info(container)
    infos = {'status': info['state'], 'pid': info['pid'], 'memusg': lwp.memory_usage(container)}

    # prepare a regex dict from cgroups_ext definition
    regex = {}
    for k, v in cgroup_ext.items():
        regex[k] = v[1]

    return render_template('edit.html', containers=lxc.ls(), container=container, infos=infos,
                           settings=cfg, host_memory=host_memory, storage_repos=storage_repos, regex=regex,
                           clonable_containers=lxc.listx()['STOPPED'])


@mod.route('/settings/lxc-net', methods=['POST', 'GET'])
@if_logged_in()
def lxc_net():
    """
    lxc-net (/etc/default/lxc) settings page and actions if form post request
    """
    if session['su'] != 'Yes':
        return abort(403)

    if request.method == 'POST':
        if lxc.running() == []:
            cfg = lwp.get_net_settings()
            ip_regex = '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?).(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?).(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?).(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)'

            form = {}
            for key in ['bridge', 'address', 'netmask', 'network', 'range', 'max']:
                form[key] = request.form.get(key, None)
            form['use'] = request.form.get('use', None)

            if form['use'] != cfg['use']:
                lwp.push_net_value('USE_LXC_BRIDGE', 'true' if form['use'] else 'false')

            if form['bridge'] and form['bridge'] != cfg['bridge'] and \
                    re.match('^[a-zA-Z0-9_-]+$', form['bridge']):
                lwp.push_net_value('LXC_BRIDGE', form['bridge'])

            if form['address'] and form['address'] != cfg['address'] and \
                    re.match('^%s$' % ip_regex, form['address']):
                lwp.push_net_value('LXC_ADDR', form['address'])

            if form['netmask'] and form['netmask'] != cfg['netmask'] and \
                    re.match('^%s$' % ip_regex, form['netmask']):
                lwp.push_net_value('LXC_NETMASK', form['netmask'])

            if form['network'] and form['network'] != cfg['network'] and \
                    re.match('^%s(?:/\d{1,2}|)$' % ip_regex, form['network']):
                lwp.push_net_value('LXC_NETWORK', form['network'])

            if form['range'] and form['range'] != cfg['range'] and \
                    re.match('^%s,%s$' % (ip_regex, ip_regex), form['range']):
                lwp.push_net_value('LXC_DHCP_RANGE', form['range'])

            if form['max'] and form['max'] != cfg['max'] and \
                    re.match('^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$', form['max']):
                lwp.push_net_value('LXC_DHCP_MAX', form['max'])

            if lwp.net_restart() == 0:
                flash(u'LXC Network settings applied successfully!', 'success')
            else:
                flash(u'Failed to restart LXC networking.', 'error')
        else:
            flash(u'Stop all containers before restart lxc-net.', 'warning')
    return render_template('lxc-net.html', containers=lxc.ls(), cfg=lwp.get_net_settings(), running=lxc.running())


@mod.route('/lwp/users', methods=['POST', 'GET'])
@if_logged_in()
def lwp_users():
    """
    returns users and get posts request : can edit or add user in page.
    this funtction uses sqlite3
    """
    if session['su'] != 'Yes':
        return abort(403)

    if AUTH != 'database':
        return abort(403, 'You are using an auth method other that database.')

    try:
        trash = request.args.get('trash')
    except KeyError:
        trash = 0

    su_users = query_db("SELECT COUNT(id) as num FROM users WHERE su='Yes'", [], one=True)

    if request.args.get('token') == session.get('token') and int(trash) == 1 and request.args.get('userid') and \
            request.args.get('username'):
        nb_users = query_db("SELECT COUNT(id) as num FROM users", [], one=True)

        if nb_users['num'] > 1:
            if su_users['num'] <= 1:
                su_user = query_db("SELECT username FROM users WHERE su='Yes'", [], one=True)

                if su_user['username'] == request.args.get('username'):
                    flash(u'Can\'t delete the last admin user : %s' % request.args.get('username'), 'error')
                    return redirect(url_for('main.lwp_users'))

            g.db.execute("DELETE FROM users WHERE id=? AND username=?", [request.args.get('userid'),
                                                                         request.args.get('username')])
            g.db.commit()
            flash(u'Deleted %s' % request.args.get('username'), 'success')
            return redirect(url_for('main.lwp_users'))

        flash(u'Can\'t delete the last user!', 'error')
        return redirect(url_for('main.lwp_users'))

    if request.method == 'POST':
        users = query_db('SELECT id, name, username, su FROM users ORDER BY id ASC')

        if request.form['newUser'] == 'True':
            if not request.form['username'] in [user['username'] for user in users]:
                if re.match('^\w+$', request.form['username']) and request.form['password1']:
                    if request.form['password1'] == request.form['password2']:
                        if request.form['name']:
                            if re.match('[a-z A-Z0-9]{3,32}', request.form['name']):
                                g.db.execute("INSERT INTO users (name, username, password) VALUES (?, ?, ?)",
                                             [request.form['name'], request.form['username'],
                                              hash_passwd(request.form['password1'])])
                                g.db.commit()
                            else:
                                flash(u'Invalid name!', 'error')
                        else:
                            g.db.execute("INSERT INTO users (username, password) VALUES (?, ?)",
                                         [request.form['username'], hash_passwd(request.form['password1'])])
                            g.db.commit()

lwp/templates/index.html
{% set td = {'running':'success','frozen':'info','stopped':'important'} %}
{% set tr = {'running':'success','frozen':'info','stopped':'error'} %}
{% set disabled = {'running':'success','frozen':'info','stopped':'important'} %}
{% extends "layout.html" %}
{% block title %}Overview{% endblock %}
{% block content %}
<div class="span9">
    {{ super() }}

    <div class="hero-unit">
        <div class="row buttons">
            {% if session.su == 'Yes' %}
            <span class="pull-right"><a class="btn btn-small btn-danger" data-toggle="modal" data-target="#reboot"> <i class="icon-off icon-white"></i> Reboot</a></span>
            {% if containers != [] %}
                <span class="pull-right"><a class="btn btn-small btn-inverse" data-toggle="modal" data-target="#cloneCT"> <i class="icon-repeat icon-white"></i> Clone <abbr title="Container">CT</abbr></a></span>
                {% if storage_repos %}
                    <span class="pull-right"><a class="btn btn-small btn-primary" data-toggle="modal" data-target="#backupCT"> <i class="icon-hdd icon-white"></i> Backup <abbr title="Container">CT</abbr></a></span>
                {% endif %}
            {% endif %}
            <span class="pull-right"><a class="btn btn-small btn-success" data-toggle="modal" data-target="#createCT"><i class="icon-plus-sign icon-white"></i> Create <abbr title="Container">CT</abbr></a></span>
            {% endif %}
        </div>
        <div class="row">
            <h3 style="margin-left: 10px">{{ dist }} ({{ host }})</h3>
            <div class="span4">
                <p>CPU usage : <span id="cpu-usage" class="hide"></span></p>
                <div class="progress">
                    <div class="bar" id="cpu-usage-bar"></div>
                </div>
                <p>Memory usage : <span id="memory-usage" class="hide"></span></p>
                <div class="progress">
                    <div class="bar" id="memory-usage-bar"></div>
                    <abbr title="Cached memory"><div class="bar bar-success" id="memory-cache-usage-bar"></div></abbr>
                </div>
            </div>
            <div class="span4">
                <p>Disk usage : <span id="disk-usage" class="hide"></span></p>
                <div class="progress">
                    <div class="bar" id="disk-usage-bar"></div>
                </div>
                <p>Uptime : <span id="uptime" class="hide"></span></p>
            </div>
        </div>
    </div>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th class="hidden-phone">Status</th>
                <th>Name</th>
                <th class="hidden-phone">Hostname</th>
                <th>IP Address</th>
                <th>Mem. usage</th>
                <th class="hidden-phone">Auto Start</th>
                <th>Actions</th>
            </tr>
        </thead>
        {% for status in containers_all %}
            <tbody>
                {% for container in status.containers %}
                    <tr class="{{ tr[status.status] }}">
                        {% if loop.first %}<td rowspan="{{ status.containers|count }}" class="hidden-phone"><span class="label label-{{ td[status.status] }}">{{ status.status|capitalize }}</span></td>{% endif %}
                        <td><a href="{{ url_for('main.edit',container=container.name) }}" title="Click to edit {{container.name}}">{{container.name}}</a></td>
                        <td class="hidden-phone">{{container.settings.utsname}}</td>
                        <td>{% if container.settings.ipv4  %}{{container.settings.ipv4}}{% else %}-{% endif %}</td>
                        <td id="{{container.name}}">{{ render_memory_wrapper(container.memusg, container.settings.memlimit) }}</td>
                        <td class="hidden-phone">
                            {% if container.settings.start_auto == '1' %}
                                <i class="icon-ok"></i>
                                {% if container.settings.start_order %} {{ container.settings.start_order }} {% endif %}
                            {% else %}
                                -
                            {% endif %}
                        </td>
                        <td>
                            <div class="btn-toolbar" style="margin:8px 0;">
                                <div class="btn-group">
                                    {% set start_action = {'stopped':'start','frozen':'unfreeze'} %}
                                    <a class="btn btn-small{% if status.status == 'running' %} disabled{% endif %}"{% if status.status == 'stopped' or status.status == 'frozen' %} href="{{ url_for('main.action', name=container.name, action=start_action[status.status]) }}"{% endif %}><i class="icon-play"></i> Start</a>
                                    <a class="btn btn-small{% if status.status == 'stopped' %} disabled{% endif %}"{% if status.status == 'running' or status.status == 'frozen' %} href="{{ url_for('main.action', name=container.name, action='stop') }}"{% endif %}><i class="icon-stop"></i> Stop</a>
                                    <a class="btn btn-small{% if status.status == 'frozen' or status.status == 'stopped' %} disabled{% endif %} hidden-phone"{% if status.status == 'running' %} href="{{ url_for('main.action', name=container.name, action='freeze') }}"{% endif %}><i class="icon-pause"></i> Freeze</a>
                                </div>
                                {% if session.su == 'Yes' and status.status == 'stopped' %}<a class="pull-right close destroy" data-container-name="{{container.name}}" style="margin-top:4px;"><i class="icon-remove-sign"></i></a>{% endif %}
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        {% endfor %}
    </table>
</div>
{% if session.su == 'Yes' %}
    {% include "includes/modal_reboot.html" %}
    {% include "includes/modal_create.html" %}

    {% if containers != [] %}
        {% include "includes/modal_clone.html" %}
        {% include "includes/modal_backup.html" %}
        {% include "includes/modal_destroy.html" %}
    {% endif %}
{% endif %}

{% endblock %}

{% macro memory_color(value) -%}{% if value != 0 %}{% if 0 <= value <= 511 %}success{% elif 512 <= value < 980 %}warning{% else %}important{% endif %}{% endif %}{%- endmacro %}
{% macro render_memory_wrapper(value, limit) -%}
    {% if value != 0 %}
        <span class="label label-{{ memory_color(value) }}">{{ value }}{% if limit != '' %} / {{ limit }}{% endif %} MB</span>
    {% else %}
        <span class="label label-success"></span>
    {% endif %}
{%- endmacro %}

{% block script %}
<script type="text/javascript">
            function refreshMemoryHost(){
                $.getJSON('{{ url_for('main.refresh_memory_containers', name='host') }}', function(data) {
                    $('#memory-usage').text(data.used +' / '+ data.total +' MB').fadeIn();
                    $('#memory-usage-bar').css({'width':data.percent+'%'});
                    $('#memory-cache-usage-bar').css({'width':data.percent_cached+'%'});

                    refreshMemoryContainers()
                });
            }

            function refreshMemoryContainers(){
                $.getJSON('{{ url_for('main.refresh_memory_containers', name='containers') }}', function(data) {
                    data = data.data;
                    for (i in data) {
                        var el = $('#'+data[i].name+' span');
                        if (data[i].settings.memlimit == '') {
                            el.text(data[i].memusg + ' MB');
                        } else {
                            el.text(data[i].memusg + " / " + data[i].settings.memlimit + ' MB');
                        }
                        el[0].className = el[0].className.replace(/label\-(success|warning|important)/g,'label-'+memory_color(data[i].memusg, data[i].settings.memlimit));
                    }
                });

                $('#home-load').fadeOut();
            }

            function memory_color(value, total){
                if(total == '') {
                    if(value != 0)
                        if ('0' <= value && value <= '512')
                            return 'success';
                        else if ('512' <= value && value < '1024')
                            return 'warning';
                        else
                            return 'important';
                }
                else {
                    value = value / total;
                    if (0 <= value && value <= 0.6)
                         return 'success';
                    else if (0.6 <= value && value < 0.8)
                        return 'warning';
                    else
                        return 'important';
                }
            }

            function refresh(){
                $('#home-load').fadeIn();

                $.getJSON('{{ url_for('main.refresh_info') }}', function(data) {
                    $('#uptime').text(data.uptime.day +' day(s) '+ data.uptime.time).fadeIn();

                    $('#cpu-usage').text(data.cpu +'%').fadeIn();
                    $('#cpu-usage-bar').css({'width':data.cpu + '%'});

                    $('#disk-usage').text(data.disk.used +' ('+ data.disk.free +' free)').fadeIn();
                    $('#disk-usage-bar').css({'width':data.disk.percent});

                    refreshMemoryHost()
                });
            }

            $(function() {
                refresh();
                {% if session.su == 'Yes' and containers == [] %}$('#createCT').modal('show'){% endif %}
                window.setInterval('refresh()', 15000);
            });

            {% if session.su == 'Yes' %}$(document).ready(function(){

                $(".destroy").on('click',function(e){
                    $(".destroy-link").attr('href',"{{url_for('main.action', action='destroy') }}" + "&name=" + $(this).data('container-name'));
                    $('.modal-body #destroy-container-name').text($(this).data('container-name'));
                    $('#destroy').modal('show');
                });

                // Create CT
                $('#advancedcreate').click(function(e){ e.preventDefault(); $('#advancedcreatediv').slideToggle(); });

                // Clone CT
                $('#advancedclone').click(function(e){ e.preventDefault(); $('#advancedclonediv').slideToggle(); });

                $(".backingstore").on('change',function(){
                        var _val = $(this).val();
                        var _lvm = $(this).closest('.advanced-wrapper').find('.lvm');
                        var _zfs = $(this).closest('.advanced-wrapper').find('.zfs');
                        var _directory = $(this).closest('.advanced-wrapper').find('.directory');

                        if( _val == 'lvm'){
                            _lvm.slideDown();
                            _directory.slideUp();
                            _zfs.slideUp();
                        }
                        else if ( _val == 'directory' ){
                            _directory.slideDown();
                            _lvm.slideUp();
                            _zfs.slideUp();
                        }
                        else if ( _val == 'zfs'){
                            _zfs.slideDown();
                            _lvm.slideUp();
                            _directory.slideUp();
                        }
                        else{
                            _zfs.slideUp();
                            _directory.slideUp();
                            _lvm.slideUp();
                        }
                    });

                    $('.modalbutton').on('click', function () {
                        $('.buttons-modal-footer').slideUp()
                        $('.loader-modal-footer').slideDown()
                    })
            });{% endif %}
</script>
{% endblock %}

lwp/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %} - LXC Web Panel</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">

    <link href="{{ url_for('static', filename='css/vendor.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/site.css') }}" rel="stylesheet">

    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="{{ url_for('static', filename='ico/favicon.ico') }}">
</head>

<body>
<div id="wrap">

    {% if session.logged_in %}
    {% include "includes/nav.html" %}
    {% endif %}


    <div class="container">
        <div class="row">
            {% if session.logged_in %}
            {% include "includes/aside.html" %}
            {% endif %}

            {% block content %}
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
            {% endblock %}
        </div>
    </div>

    <div id="push"></div>
</div>

<div id="footer">
    <div class="container">
        <p class="muted credit"><small class="easteregg">LXC Web Panel &copy; 2014{% if 'logged_in' in session %} - <a href="{{ url_for('main.about') }}" class="muted">MIT License</a>{% endif %}</small></p>
    </div>
</div>

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{{ url_for('static', filename='js/vendor.min.js') }}"></script>
<script>
                $(function() {
                        $(".alert").not('.dont-hide').alert().delay(5000).slideUp();
                        $("#home-btn").on('click',function(){
                                $('#home-load').fadeIn();
                        });
                        $("input").not("[type=submit]").jqBootstrapValidation();
                        $("[type=checkbox]").bootstrapSwitch();
                        $(".easteregg").click(function(){
                            $("head").append($("<link href=\"http://code.divshot.com/geo-bootstrap/swatch/bootstrap.min.css\" rel=\"stylesheet\">"));
                        });
                });
        </script>
{% block script %}{% endblock %}
</body>
</html>

lwp/templates/lxc-net.html
{% extends "layout.html" %}
{% block title %}Networking{% endblock %}
{% block content %}
<div class="span9">
    {{ super() }}
    <form id="config" class="form-horizontal" action="{{ url_for('main.lxc_net') }}" method="post">
        <h3 class="head head-networking">LXC Network</h3>
        <div class="control-group switch-networking">
            <div class="controls" style="margin-left: 5px;">
                <div class="switch" data-on-label="<i class='icon-ok icon-white'></i>" data-off-label="<i class='icon-remove icon-white'></i>" data-on="success" data-off="danger">
                    <input type="checkbox" name="use" value="true" {% if cfg.use == 'true' %}checked{% endif %}{% if running != [] %} disabled{% endif %} />
                </div>
            </div>
        </div>

        {% if running != [] %}<h4 class="text-error">Please, stop all containers before restarting lxc-net.</h4><br />{% endif %}


        <div class="lxc-net">
            <div class="control-group">
                <label class="control-label" for="inputBridge">Bridge name</label>
                <div class="controls">
                    <input pattern="[a-zA-Z0-9_-]+" type="text" id="inputBridge" name="bridge" value="{{ cfg.bridge }}"{% if running != [] %} disabled{% endif %}>
                    <span class="help-inline"><small>(e.g lxcbr0)</small></span>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="inputGateway">IP Address</label>
                <div class="controls">
                    <input pattern="(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)" type="text" id="inputGateway" name="address" value="{{ cfg.address }}"{% if running != [] %} disabled{% endif %}>
                    <span class="help-inline"><small>(e.g 10.0.3.1)</small></span>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="inputNetmask">Netmask</label>
                <div class="controls">
                    <input pattern="(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)" type="text" id="inputNetmask" name="netmask" value="{{ cfg.netmask }}"{% if running != [] %} disabled{% endif %}>
                    <span class="help-inline"><small>(e.g 255.255.255.0)</small></span>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="inputNetwork">Network</label>
                <div class="controls">
                    <input pattern="(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(?:/\d{1,2}|)" type="text" id="inputNetwork" name="network" value="{{ cfg.network }}"{% if running != [] %} disabled{% endif %}>
                    <span class="help-inline"><small>(e.g 10.0.3.0/24)</small></span>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="inputDHCPRange">DHCP Range</label>
                <div class="controls">
                    <input pattern="(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\,(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)" type="text" id="inputDHCPRange" name="range" value="{{ cfg.range }}"{% if running != [] %} disabled{% endif %}>
                    <span class="help-inline"><small>(e.g 10.0.3.2,10.0.3.254)</small></span>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="inputDHCPMax">DHCP Max</label>
                <div class="controls">
                    <input pattern="(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)" type="text" id="inputDHCPMax" name="max" value="{{ cfg.max }}"{% if running != [] %} disabled{% endif %}>
                    <span class="help-inline"><small>(e.g 253)</small></span>
                </div>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <button class="btn btn-primary btn-success" name="submit" value="apply" type="submit"{% if running != [] %} disabled{% endif %}><i class="icon-ok icon-white"></i> Apply</button>
                <span class="help-inline"><small>If you change these settings, don't forget to change containers addresses!</small></span>
            </div>
        </div>
    </form>

</div>
{% endblock %}
{% block script %}
    <script type="text/javascript">
        $(document).ready(function(){
            var networking = $(".lxc-net");
            var inputText = $("input[type='text']");

            if ('{{cfg.use}}' == 'false') {
                inputText.attr('disabled', 'disabled');
                networking.fadeTo(0, 0.4);
            }

            $(".switch-networking").on('switch-change', function(e, data){
                if(data.value){
                    inputText.removeAttr('disabled');
                    networking.fadeTo(400, 1);
                }
                else{
                    inputText.attr('disabled', 'disabled');
                    networking.fadeTo(400, 0.4);
                }
            });
        });
    </script>
{% endblock %}